#!/bin/sh

#eliminar ciertos fichero que puedan provocar errores en la desinstalacion
if [ -f /usr/bin/drManhattan/drAlu.key]; then
	rm /usr/bin/drManhattan/drAlu.key
fi

if [ -f /usr/bin/drManhattan/drAlu.dat]; then	
	rm /usr/bin/drManhattan/drAlu.dat	
fi

ps -ef | grep drManhattanDaemon.jar | grep -v grep | awk '{print $2}' | xargs kill -9 #mata al demonio

